INFO  2022-01-04 16:16:43,678 wx_minium.py launch_dev_tool 692 Starting dev tool and launch MiniProgram project ...
WARNI 2022-01-04 16:16:43,678 wx_minium.py launch_dev_tool 734 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2022-01-04 16:16:43,678 wx_minium.py launch_dev_tool 738 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2022-01-04 16:16:43,679 wx_minium.py connect_dev_tool 785 Trying to connect Dev tool ...
ERROR 2022-01-04 16:16:43,712 connection.py _on_error       265 [Errno 61] Connection refused
INFO  2022-01-04 16:16:43,719 connection.py _ws_run_forever 151 websocket run forever shutdown
ERROR 2022-01-04 16:17:18,778 wx_minium.py connect_dev_tool 798 connect to server timeout: ws://localhost:9420, thread:False
Traceback (most recent call last):
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/wx_minium.py", line 786, in connect_dev_tool
    connection = Connection(self.uri, timeout=self.conf.get("request_timeout"))
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 87, in __init__
    self._connect()
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 140, in _connect
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: connect to server timeout: ws://localhost:9420, thread:False
INFO  2022-01-04 16:17:18,782 wx_minium.py connect_dev_tool 785 Trying to connect Dev tool ...
ERROR 2022-01-04 16:17:18,819 connection.py _on_error       265 [Errno 61] Connection refused
INFO  2022-01-04 16:17:18,837 connection.py _ws_run_forever 151 websocket run forever shutdown
ERROR 2022-01-04 16:17:49,628 wx_minium.py connect_dev_tool 798 connect to server timeout: ws://localhost:9420, thread:False
Traceback (most recent call last):
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/wx_minium.py", line 786, in connect_dev_tool
    connection = Connection(self.uri, timeout=self.conf.get("request_timeout"))
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 87, in __init__
    self._connect()
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 140, in _connect
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: connect to server timeout: ws://localhost:9420, thread:False
INFO  2022-01-04 16:17:49,629 wx_minium.py connect_dev_tool 785 Trying to connect Dev tool ...
ERROR 2022-01-04 16:17:49,654 connection.py _on_error       265 [Errno 61] Connection refused
INFO  2022-01-04 16:17:49,654 connection.py _ws_run_forever 151 websocket run forever shutdown
ERROR 2022-01-04 16:18:20,142 wx_minium.py connect_dev_tool 798 connect to server timeout: ws://localhost:9420, thread:False
Traceback (most recent call last):
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/wx_minium.py", line 786, in connect_dev_tool
    connection = Connection(self.uri, timeout=self.conf.get("request_timeout"))
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 87, in __init__
    self._connect()
  File "/Users/dongman/PycharmProjects/dongmanworkproject/venv/lib/python3.10/site-packages/minium/miniprogram/base_driver/connection.py", line 140, in _connect
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: connect to server timeout: ws://localhost:9420, thread:False
ERROR 2022-01-04 16:18:22,037 wx_minium.py launch_dev_tool 748 three times try to connect Dev tool has all fail ..., restart now...
